name: noscribe-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pillow
  - pyyaml
  - appdirs
  - typing
  - pathlib
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pyinstaller
  - pip
  - pip:
    - elevate
    - python-i18n
    - git+https://github.com/kaixxx/python-docx
    - git+https://github.com/kaixxx/pyannote-audio
    - auto-py-to-exe
